### ISSUE TITLE
Error when installing asreview-wordcloud

### ISSUE THREAD

**Issue by FioByr** [asreview/asreview-wordcloud#14]
I get this error when I attempt to install asreview-wordcloud in my Command Prompt on Windows.

![Screenshot 2023-05-01 165640](https://user-images.githubusercontent.com/130690832/235474409-5c68c31e-5a20-4b99-a6c7-0f0799aa6cc8.png)

I have been able to install asreview and the other tools without any problem. Can anyone help me with this?

**Comment by J535D165** [comment]
Can you copy-paste the full error in a code block (see the buttons above the text insert field) in this thread? This includes the insert statement :)

**Comment by FioByr** [comment]
I can install it now. I installed Microsoft Visual C++ as it mentioned in the error, and it now seems to work properly.

**Comment by zoneout215** [comment]
Looks like you have an issue with the wheel of the "wordcloud" package. There is a big discussion on [github repo of one developer](https://github.com/amueller/word_cloud/issues/105). I also had the same issue, and my solution was to download the wheel file from this [archive](https://github.com/amueller/word_cloud/issues/105), and run this command with your python module: 
```
python -m pip install <the wheel file path>
```
or if you are a Windows user
```
python.exe  -m pip install wordcloud
```

Other solution that wonder in the discussions is to install [Microsoft Visual C++ Compiler](https://github.com/amueller/word_cloud/issues/105#issuecomment-163358854), but in my opinon it's an overkill, in terms of memory.

**Comment by FioByr** [comment]
> Looks like you have an issue with the wheel of the "wordcloud" package. There is a big discussion on [github repo of one developer](https://github.com/amueller/word_cloud/issues/105). I also had the same issue, and my solution was to download the wheel file from this [archive](https://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud), and run this command with your python module:
> 
> ```
> python -m pip install <the wheel file path>
> ```
> 
> or if you are a Windows user
> 
> ```
> python.exe  -m pip install wordcloud
> ```
> 
> Other solution that wonder in the [discussions](https://github.com/amueller/word_cloud/issues/105#issuecomment-163358854) is to install Microsoft Visual C++ Compiler, but in my opinon it's an overkill in terms of memory.

Thank you Sergei! This worked for me too
